<?xml version="1.0" encoding="utf-8"?>
<pysystest type="auto">

    <description>
        <title>Error: response when calling getStorageAt</title>
        <purpose><![CDATA[
Deploys a game contract with a secret number, then attempts to get the secret number using a call to
get_storage_at. On other chains this allows the user to cheat, whereas on ten we expect an illegal access exception
to be thrown.
]]>
        </purpose>
    </description>

    <classification>
        <groups inherit="true">
        </groups>
        <modes inherit="true">
            <mode>ten.sepolia</mode>
            <mode>ten.uat</mode>
            <mode>ten.dev</mode>
            <mode>ten.local</mode>
            <mode>ten.sim</mode>
            <mode>ganache</mode>
        </modes>
    </classification>

    <data>
        <class name="PySysTest" module="run"/>
    </data>

    <traceability>
        <requirements>
            <requirement id=""/>
        </requirements>
    </traceability>
</pysystest>
