# Check key balances on sepolia-testnet
#
name: '[inspect] Check sepolia funds'
run-name: Check sepolia-testnet funds
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, all-testnets]
    env:
      RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: 'Check out ten-test'
        uses: actions/checkout@v3
        with:
          path: ./ten-test

      - name: 'Check out go-ten code'
        uses: actions/checkout@v3
        with:
          repository: ten-protocol/go-ten
          path: ./go-ten
          ref: 'releases/v1.0'

      - name: 'Build required artifacts for running tests'
        run: |
          cd ${{ github.workspace }}/ten-test
          ./get_artifacts.sh
          ls -l ${{ github.workspace }}/ten-test/artifacts  

      - name: 'Run funds check'
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -r -m ten.sepolia -XRUN_TYPE=funds check_funds

      - name: 'Alert on funds check'
        if: always()
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m ten.sepolia -XRUN_TYPE=funds -XRUN_NAME=Funds_health -XRUN_URL=$RUN_URL -XNO_CONNECT alert_support

      - name: 'Discord notification on failure'
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.TESTNET_HEALTH_WEBHOOK }}
          title: "The health_check_sepolia_funds.yml workflow has failed"
          description: "The workflow shows failures and so requires investigation"
          content: "For information <@814873419207409685> <@92361563276591104> <@920586981581393983> <@921049923414261821> <@1034771491436363797> <@639076633994592256>  <@1275573709910052947> <@398020680966471680> <@216439743947341824>"
          avatar_url: ${{ secrets.AVATAR_URL }}



